remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: "Martin Delille"
description: "The blog I always dreamed to write."
logo: "/images/martindelille.jpg"
read_time: true
words_per_minute: 200

# Liquid
liquid:
  error_mode: strict

# Build settings
kramdown:
  show_warnings: true

feed:
  path: /atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Taxonomy pages
tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  posts:
    permalink: /:categories/:year/:month/:day/:title/

# Site Author
author:
  name: Martin Delille
  picture: /images/martindelille.jpg
  email: martin@delille.io
  twitter: martinodelilo
  links:
    - title: Twitter
      url: https://twitter.com/martinodelilo
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/martindelille
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/martindelille
      icon: fab fa-github-square
