name: HTML Proofer

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.86.0
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - run: bundle exec rake html_proofer
